name: Postman Collection workflow

on:
  push:
    branches:
      - main

jobs:
  newman_run:
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1   
        with:
           node-version: '18'
           
      - name: Install Newman & HTML reporter 
        run: |
            npm install -g newman
            npm install -g newman-reporter-htmlextra
      - name: Run tests
        run: |
          newman run Iskakova.postman_collection.json -e Iskakova.postman_environment.json -r cli,htmlextra,junit
     
      # - name: Archive results
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: newman-results
      #     path: results.xml
      - name: Checkout to gh-pages branch
        if: always()
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Iskakova report
        if: always()
        run: |
          ls
          pwd
          cd newman
          mv *.html index.html
      
      - name: Host report to the gh-pages branch
        if: always()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: newman
        env:
          GITHUB_TOKEN: ${{ token }}
      
      - name: Deploy the report from the gh-pages branch to the website
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ token }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: newman
      
